// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using findamodel.Data;

#nullable disable

namespace findamodel.Migrations
{
    [DbContext(typeof(ModelCacheContext))]
    [Migration("20260302013032_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.13");

            modelBuilder.Entity("findamodel.Data.Entities.CachedModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CachedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Checksum")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ConcaveHullCoordinates")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConvexHullCoordinates")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConvexSansRaftHullCoordinates")
                        .HasColumnType("TEXT");

                    b.Property<float?>("DimensionXMm")
                        .HasColumnType("REAL");

                    b.Property<float?>("DimensionYMm")
                        .HasColumnType("REAL");

                    b.Property<float?>("DimensionZMm")
                        .HasColumnType("REAL");

                    b.Property<string>("Directory")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("DirectoryConfigId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FileModifiedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("FileSize")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FileType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("GeometryCalculatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("HullGeneratedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("PreviewGeneratedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("PreviewImagePath")
                        .HasColumnType("TEXT");

                    b.Property<float?>("SphereCentreX")
                        .HasColumnType("REAL");

                    b.Property<float?>("SphereCentreY")
                        .HasColumnType("REAL");

                    b.Property<float?>("SphereCentreZ")
                        .HasColumnType("REAL");

                    b.Property<float?>("SphereRadius")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("Checksum");

                    b.HasIndex("DirectoryConfigId");

                    b.ToTable("Models");
                });

            modelBuilder.Entity("findamodel.Data.Entities.DirectoryConfig", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .HasColumnType("TEXT");

                    b.Property<string>("Collection")
                        .HasColumnType("TEXT");

                    b.Property<string>("Creator")
                        .HasColumnType("TEXT");

                    b.Property<string>("DirectoryPath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LocalConfigFileHash")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RawCategory")
                        .HasColumnType("TEXT");

                    b.Property<string>("RawCollection")
                        .HasColumnType("TEXT");

                    b.Property<string>("RawCreator")
                        .HasColumnType("TEXT");

                    b.Property<string>("RawSubcollection")
                        .HasColumnType("TEXT");

                    b.Property<bool?>("RawSupported")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RawType")
                        .HasColumnType("TEXT");

                    b.Property<string>("Subcollection")
                        .HasColumnType("TEXT");

                    b.Property<bool?>("Supported")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Type")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DirectoryPath")
                        .IsUnique();

                    b.HasIndex("ParentId");

                    b.ToTable("DirectoryConfigs");
                });

            modelBuilder.Entity("findamodel.Data.Entities.PrintingList", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.ToTable("PrintingLists");
                });

            modelBuilder.Entity("findamodel.Data.Entities.PrintingListItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ModelId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PrintingListId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PrintingListId");

                    b.ToTable("PrintingListItems");
                });

            modelBuilder.Entity("findamodel.Data.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("findamodel.Data.Entities.CachedModel", b =>
                {
                    b.HasOne("findamodel.Data.Entities.DirectoryConfig", "DirectoryConfig")
                        .WithMany("Models")
                        .HasForeignKey("DirectoryConfigId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("DirectoryConfig");
                });

            modelBuilder.Entity("findamodel.Data.Entities.DirectoryConfig", b =>
                {
                    b.HasOne("findamodel.Data.Entities.DirectoryConfig", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("findamodel.Data.Entities.PrintingList", b =>
                {
                    b.HasOne("findamodel.Data.Entities.User", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("findamodel.Data.Entities.PrintingListItem", b =>
                {
                    b.HasOne("findamodel.Data.Entities.PrintingList", "PrintingList")
                        .WithMany("Items")
                        .HasForeignKey("PrintingListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PrintingList");
                });

            modelBuilder.Entity("findamodel.Data.Entities.DirectoryConfig", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("Models");
                });

            modelBuilder.Entity("findamodel.Data.Entities.PrintingList", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
