// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using findamodel.Data;

#nullable disable

namespace findamodel.Migrations
{
    [DbContext(typeof(ModelCacheContext))]
    [Migration("20260419193444_AddAutoSupportForceSettings")]
    partial class AddAutoSupportForceSettings
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.6");

            modelBuilder.Entity("findamodel.Data.Entities.AppConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AiDescriptionEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<float>("AutoSupportAreaGrowthMultiplier")
                        .HasColumnType("REAL");

                    b.Property<float>("AutoSupportAreaGrowthThreshold")
                        .HasColumnType("REAL");

                    b.Property<float>("AutoSupportBedMarginMm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("REAL")
                        .HasDefaultValue(2f);

                    b.Property<float>("AutoSupportCrushForceThreshold")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("REAL")
                        .HasDefaultValue(20f);

                    b.Property<float>("AutoSupportDragCoefficientMultiplier")
                        .HasColumnType("REAL");

                    b.Property<bool>("AutoSupportGravityEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<float>("AutoSupportHeavyTipRadiusMm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("REAL")
                        .HasDefaultValue(1.5f);

                    b.Property<float>("AutoSupportLightTipRadiusMm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("REAL")
                        .HasDefaultValue(0.7f);

                    b.Property<float>("AutoSupportMaxAngularForce")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("REAL")
                        .HasDefaultValue(40f);

                    b.Property<float>("AutoSupportMaxLayerHeightMm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("REAL")
                        .HasDefaultValue(1.5f);

                    b.Property<float>("AutoSupportMaxSupportDistanceMm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("REAL")
                        .HasDefaultValue(10f);

                    b.Property<int>("AutoSupportMaxSupportsPerIsland")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(6);

                    b.Property<float>("AutoSupportMaxVoxelSizeMm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("REAL")
                        .HasDefaultValue(2f);

                    b.Property<float>("AutoSupportMediumTipRadiusMm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("REAL")
                        .HasDefaultValue(1f);

                    b.Property<float>("AutoSupportMergeDistanceMm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("REAL")
                        .HasDefaultValue(2.5f);

                    b.Property<float>("AutoSupportMicroTipRadiusMm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("REAL")
                        .HasDefaultValue(0.4f);

                    b.Property<float>("AutoSupportMinFeatureWidthMm")
                        .HasColumnType("REAL");

                    b.Property<float>("AutoSupportMinIslandAreaMm2")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("REAL")
                        .HasDefaultValue(4f);

                    b.Property<float>("AutoSupportMinLayerHeightMm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("REAL")
                        .HasDefaultValue(0.75f);

                    b.Property<float>("AutoSupportMinVoxelSizeMm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("REAL")
                        .HasDefaultValue(0.8f);

                    b.Property<float>("AutoSupportPeelForceMultiplier")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("REAL")
                        .HasDefaultValue(0.15f);

                    b.Property<float>("AutoSupportPullForceThreshold")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("REAL")
                        .HasDefaultValue(3f);

                    b.Property<float>("AutoSupportResinDensityGPerMl")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("REAL")
                        .HasDefaultValue(1.25f);

                    b.Property<float>("AutoSupportResinStrength")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("REAL")
                        .HasDefaultValue(1f);

                    b.Property<float>("AutoSupportShrinkageEdgeBias")
                        .HasColumnType("REAL");

                    b.Property<float>("AutoSupportShrinkagePercent")
                        .HasColumnType("REAL");

                    b.Property<float>("AutoSupportSphereRadiusMm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("REAL")
                        .HasDefaultValue(1.2f);

                    b.Property<float>("AutoSupportSuctionMultiplier")
                        .HasColumnType("REAL");

                    b.Property<float>("AutoSupportUnsupportedIslandVolumeThresholdMm3")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("REAL")
                        .HasDefaultValue(1f);

                    b.Property<float>("AutoSupportV2CoarseVoxelSizeMm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("REAL")
                        .HasDefaultValue(4f);

                    b.Property<float>("AutoSupportV2FineVoxelSizeMm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("REAL")
                        .HasDefaultValue(0.5f);

                    b.Property<float>("AutoSupportV2MinRegionVolumeMm3")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("REAL")
                        .HasDefaultValue(8f);

                    b.Property<bool>("AutoSupportV2OptimizationEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<float>("AutoSupportV2RefinementMarginMm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("REAL")
                        .HasDefaultValue(2f);

                    b.Property<int>("AutoSupportV2RefinementMaxRegions")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(12);

                    b.Property<float>("AutoSupportV2RiskForceMarginRatio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("REAL")
                        .HasDefaultValue(0.2f);

                    b.Property<float>("AutoSupportV2VoxelSizeMm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("REAL")
                        .HasDefaultValue(2f);

                    b.Property<float>("DefaultRaftHeightMm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("REAL")
                        .HasDefaultValue(2f);

                    b.Property<string>("DescriptionGenerationPromptTemplate")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("GeneratePreviewsEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<int>("MinimumPreviewGenerationVersion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(9);

                    b.Property<string>("ModelsDirectoryPath")
                        .HasColumnType("TEXT");

                    b.Property<bool>("SetupCompleted")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("TagGenerationEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<string>("TagGenerationEndpoint")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("http://localhost:11434");

                    b.Property<int>("TagGenerationMaxTags")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(12);

                    b.Property<float>("TagGenerationMinConfidence")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("REAL")
                        .HasDefaultValue(0.45f);

                    b.Property<string>("TagGenerationModel")
                        .HasColumnType("TEXT");

                    b.Property<string>("TagGenerationPromptTemplate")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TagGenerationProvider")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("internal");

                    b.Property<int>("TagGenerationTimeoutMs")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(60000);

                    b.Property<string>("Theme")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("AppConfigs");
                });

            modelBuilder.Entity("findamodel.Data.Entities.CachedModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CachedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CalculatedCategory")
                        .HasColumnType("TEXT");

                    b.Property<string>("CalculatedCollection")
                        .HasColumnType("TEXT");

                    b.Property<string>("CalculatedCreator")
                        .HasColumnType("TEXT");

                    b.Property<string>("CalculatedMaterial")
                        .HasColumnType("TEXT");

                    b.Property<string>("CalculatedModelName")
                        .HasColumnType("TEXT");

                    b.Property<string>("CalculatedPartName")
                        .HasColumnType("TEXT");

                    b.Property<string>("CalculatedSubcollection")
                        .HasColumnType("TEXT");

                    b.Property<bool?>("CalculatedSupported")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CalculatedTagsJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("CalculatedType")
                        .HasColumnType("TEXT");

                    b.Property<string>("Checksum")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ConcaveHullCoordinates")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConvexHullCoordinates")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConvexSansRaftHullCoordinates")
                        .HasColumnType("TEXT");

                    b.Property<float?>("DimensionXMm")
                        .HasColumnType("REAL");

                    b.Property<float?>("DimensionYMm")
                        .HasColumnType("REAL");

                    b.Property<float?>("DimensionZMm")
                        .HasColumnType("REAL");

                    b.Property<string>("Directory")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("DirectoryConfigId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FileModifiedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("FileSize")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FileType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("GeneratedDescription")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("GeneratedDescriptionAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("GeneratedDescriptionChecksum")
                        .HasColumnType("TEXT");

                    b.Property<string>("GeneratedDescriptionModel")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("GeneratedTagsAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("GeneratedTagsChecksum")
                        .HasColumnType("TEXT");

                    b.Property<string>("GeneratedTagsConfidenceJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("GeneratedTagsError")
                        .HasColumnType("TEXT");

                    b.Property<string>("GeneratedTagsJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("GeneratedTagsModel")
                        .HasColumnType("TEXT");

                    b.Property<string>("GeneratedTagsStatus")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("GeometryCalculatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("HullGeneratedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("HullGenerationVersion")
                        .HasColumnType("INTEGER");

                    b.Property<float?>("HullRaftHeightMm")
                        .HasColumnType("REAL");

                    b.Property<DateTime?>("PreviewGeneratedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("PreviewGenerationVersion")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PreviewImagePath")
                        .HasColumnType("TEXT");

                    b.Property<string>("ScanConfigChecksum")
                        .HasColumnType("TEXT");

                    b.Property<float?>("SphereCentreX")
                        .HasColumnType("REAL");

                    b.Property<float?>("SphereCentreY")
                        .HasColumnType("REAL");

                    b.Property<float?>("SphereCentreZ")
                        .HasColumnType("REAL");

                    b.Property<float?>("SphereRadius")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("CalculatedTagsJson");

                    b.HasIndex("Checksum");

                    b.HasIndex("DirectoryConfigId");

                    b.HasIndex("Directory", "FileName")
                        .IsUnique();

                    b.HasIndex("CalculatedCreator", "CalculatedCollection", "CalculatedSubcollection", "CalculatedModelName");

                    b.ToTable("Models");
                });

            modelBuilder.Entity("findamodel.Data.Entities.DirectoryConfig", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .HasColumnType("TEXT");

                    b.Property<string>("Collection")
                        .HasColumnType("TEXT");

                    b.Property<string>("Creator")
                        .HasColumnType("TEXT");

                    b.Property<string>("DirectoryPath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LocalConfigFileHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("Material")
                        .HasColumnType("TEXT");

                    b.Property<string>("ModelName")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("TEXT");

                    b.Property<string>("PartName")
                        .HasColumnType("TEXT");

                    b.Property<float?>("RaftHeightMm")
                        .HasColumnType("REAL");

                    b.Property<string>("RawCategory")
                        .HasColumnType("TEXT");

                    b.Property<string>("RawCollection")
                        .HasColumnType("TEXT");

                    b.Property<string>("RawCreator")
                        .HasColumnType("TEXT");

                    b.Property<string>("RawMaterial")
                        .HasColumnType("TEXT");

                    b.Property<string>("RawModelMetadataJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("RawModelName")
                        .HasColumnType("TEXT");

                    b.Property<string>("RawPartName")
                        .HasColumnType("TEXT");

                    b.Property<float?>("RawRaftHeightMm")
                        .HasColumnType("REAL");

                    b.Property<string>("RawRulesYaml")
                        .HasColumnType("TEXT");

                    b.Property<string>("RawSubcollection")
                        .HasColumnType("TEXT");

                    b.Property<bool?>("RawSupported")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RawTagsJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("RawType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ResolvedRulesYaml")
                        .HasColumnType("TEXT");

                    b.Property<string>("Subcollection")
                        .HasColumnType("TEXT");

                    b.Property<bool?>("Supported")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TagsJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DirectoryPath")
                        .IsUnique();

                    b.HasIndex("ParentId");

                    b.ToTable("DirectoryConfigs");
                });

            modelBuilder.Entity("findamodel.Data.Entities.IndexRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DirectoryFilter")
                        .HasColumnType("TEXT");

                    b.Property<double?>("DurationMs")
                        .HasColumnType("REAL");

                    b.Property<string>("Error")
                        .HasColumnType("TEXT");

                    b.Property<int>("Flags")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Outcome")
                        .HasColumnType("TEXT");

                    b.Property<int>("ProcessedFiles")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RelativeModelPath")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("RequestedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("TotalFiles")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("RequestedAt");

                    b.HasIndex("Status");

                    b.ToTable("IndexRuns");
                });

            modelBuilder.Entity("findamodel.Data.Entities.IndexRunEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("IndexRunId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RelativePath")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IndexRunId", "CreatedAt");

                    b.ToTable("IndexRunEvents");
                });

            modelBuilder.Entity("findamodel.Data.Entities.IndexRunFile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AiGenerationReason")
                        .HasColumnType("TEXT");

                    b.Property<double?>("DurationMs")
                        .HasColumnType("REAL");

                    b.Property<string>("FileType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("GeneratedAiDescription")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("GeneratedAiTags")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("GeneratedHull")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("GeneratedPreview")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("IndexRunId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsNew")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Message")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("RelativePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("WasUpdated")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("IndexRunId", "RelativePath")
                        .IsUnique();

                    b.ToTable("IndexRunFiles");
                });

            modelBuilder.Entity("findamodel.Data.Entities.MetadataDictionaryValue", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Field")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedValue")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Field", "NormalizedValue")
                        .IsUnique();

                    b.HasIndex("Field", "Value");

                    b.ToTable("MetadataDictionaryValues");
                });

            modelBuilder.Entity("findamodel.Data.Entities.PrinterConfig", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<float>("BedDepthMm")
                        .HasColumnType("REAL");

                    b.Property<float>("BedWidthMm")
                        .HasColumnType("REAL");

                    b.Property<bool>("IsBuiltIn")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PixelHeight")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PixelWidth")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("IsDefault");

                    b.ToTable("PrinterConfigs");
                });

            modelBuilder.Entity("findamodel.Data.Entities.PrintingList", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("HullMode")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("convex");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("PrinterConfigId")
                        .HasColumnType("TEXT");

                    b.Property<string>("SpawnType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("grouped");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.HasIndex("PrinterConfigId");

                    b.ToTable("PrintingLists");
                });

            modelBuilder.Entity("findamodel.Data.Entities.PrintingListItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ModelId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PrintingListId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PrintingListId");

                    b.ToTable("PrintingListItems");
                });

            modelBuilder.Entity("findamodel.Data.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("findamodel.Data.Entities.CachedModel", b =>
                {
                    b.HasOne("findamodel.Data.Entities.DirectoryConfig", "DirectoryConfig")
                        .WithMany("Models")
                        .HasForeignKey("DirectoryConfigId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("DirectoryConfig");
                });

            modelBuilder.Entity("findamodel.Data.Entities.DirectoryConfig", b =>
                {
                    b.HasOne("findamodel.Data.Entities.DirectoryConfig", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("findamodel.Data.Entities.IndexRunEvent", b =>
                {
                    b.HasOne("findamodel.Data.Entities.IndexRun", "IndexRun")
                        .WithMany("Events")
                        .HasForeignKey("IndexRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IndexRun");
                });

            modelBuilder.Entity("findamodel.Data.Entities.IndexRunFile", b =>
                {
                    b.HasOne("findamodel.Data.Entities.IndexRun", "IndexRun")
                        .WithMany("Files")
                        .HasForeignKey("IndexRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IndexRun");
                });

            modelBuilder.Entity("findamodel.Data.Entities.PrintingList", b =>
                {
                    b.HasOne("findamodel.Data.Entities.User", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("findamodel.Data.Entities.PrinterConfig", "PrinterConfig")
                        .WithMany("PrintingLists")
                        .HasForeignKey("PrinterConfigId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Owner");

                    b.Navigation("PrinterConfig");
                });

            modelBuilder.Entity("findamodel.Data.Entities.PrintingListItem", b =>
                {
                    b.HasOne("findamodel.Data.Entities.PrintingList", "PrintingList")
                        .WithMany("Items")
                        .HasForeignKey("PrintingListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PrintingList");
                });

            modelBuilder.Entity("findamodel.Data.Entities.DirectoryConfig", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("Models");
                });

            modelBuilder.Entity("findamodel.Data.Entities.IndexRun", b =>
                {
                    b.Navigation("Events");

                    b.Navigation("Files");
                });

            modelBuilder.Entity("findamodel.Data.Entities.PrinterConfig", b =>
                {
                    b.Navigation("PrintingLists");
                });

            modelBuilder.Entity("findamodel.Data.Entities.PrintingList", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
