// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using findamodel.Data;

#nullable disable

namespace findamodel.Migrations
{
    [DbContext(typeof(ModelCacheContext))]
    [Migration("20260413150536_AddUniformationGK3")]
    partial class AddUniformationGK3
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("findamodel.Data.Entities.ModelCacheEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Author")
                        .HasColumnType("TEXT");

                    b.Property<string>("Categories")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("License")
                        .HasColumnType("TEXT");

                    b.Property<string>("ModelPath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Tags")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ModelPath")
                        .IsUnique();

                    b.ToTable("ModelCacheEntries");
                });

            modelBuilder.Entity("findamodel.Data.Entities.ModelMetadata", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ModelCacheEntryId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Key");

                    b.HasIndex("ModelCacheEntryId");

                    b.ToTable("ModelMetadata");
                });

            modelBuilder.Entity("findamodel.Data.Entities.PrinterConfig", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<float>("BedDepthMm")
                        .HasColumnType("REAL");

                    b.Property<float>("BedWidthMm")
                        .HasColumnType("REAL");

                    b.Property<bool>("IsBuiltIn")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IsDefault");

                    b.ToTable("PrinterConfigs");
                });

            modelBuilder.Entity("findamodel.Data.Entities.PrintingList", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ExportedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ItemPositions")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("PrinterConfigId")
                        .HasColumnType("TEXT");

                    b.Property<int>("SpawnOrder")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PrinterConfigId");

                    b.ToTable("PrintingLists");
                });

            modelBuilder.Entity("findamodel.Data.Entities.PrintingListModelRef", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ModelCacheEntryId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PrintingListId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PrintingListId");

                    b.ToTable("PrintingListModelRefs");
                });

            modelBuilder.Entity("findamodel.Data.Entities.ModelMetadata", b =>
                {
                    b.HasOne("findamodel.Data.Entities.ModelCacheEntry", null)
                        .WithMany("Metadata")
                        .HasForeignKey("ModelCacheEntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("findamodel.Data.Entities.PrintingList", b =>
                {
                    b.HasOne("findamodel.Data.Entities.PrinterConfig", "PrinterConfig")
                        .WithMany("PrintingLists")
                        .HasForeignKey("PrinterConfigId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("PrinterConfig");
                });

            modelBuilder.Entity("findamodel.Data.Entities.PrintingListModelRef", b =>
                {
                    b.HasOne("findamodel.Data.Entities.PrintingList", null)
                        .WithMany("ModelRefs")
                        .HasForeignKey("PrintingListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("findamodel.Data.Entities.ModelCacheEntry", b =>
                {
                    b.Navigation("Metadata");
                });

            modelBuilder.Entity("findamodel.Data.Entities.PrinterConfig", b =>
                {
                    b.Navigation("PrintingLists");
                });

            modelBuilder.Entity("findamodel.Data.Entities.PrintingList", b =>
                {
                    b.Navigation("ModelRefs");
                });
#pragma warning restore 612, 618
        }
    }
}
